name: Test SignPath

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-2022
    strategy:
      matrix:
        bits:
          - 32
        link:
          - shared
    env:
      CLDR_VERSION: 45
      ICONV_VERSION: 1.17
      GETTEXT_VERSION: 0.22.5a
      CYGWIN_NOWINPATH: 1
      CHERE_INVOKING: 1
    defaults:
      run:
        shell: C:\cygwin\bin\bash.exe --login -o igncr -o errexit -o pipefail {0}
    steps:
      -
        name: Configure git
        shell: cmd
        run: git config --global core.autocrlf input
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Restore cache
        id: restore-cache
        uses: actions/cache/restore@v4
        with:
          key: ${{ matrix.link }}-${{ matrix.bits }}
          path: |
            C:\cygwin-packages
            C:\cygwin\src\downloads
      -
        name: Set variables
        id: vars
        shell: pwsh
        run: ./build-exe/vars.ps1 -Bits ${{ matrix.bits }} -Link ${{ matrix.link }}
      -
        name: Download Cygwin installer
        shell: pwsh
        run: Invoke-WebRequest -Uri https://cygwin.com/setup-x86_64.exe -OutFile C:\CygwinInstaller.exe
      -
        name: Install Cygwin
        shell: cmd
        run: >
          C:\CygwinInstaller.exe
          --root C:\cygwin
          --local-package-dir C:\cygwin-packages
          --packages ${{ steps.vars.outputs.cygwin-packages }}
          --site http://mirrors.kernel.org/sourceware/cygwin/
          --only-site
          --quiet-mode
          --upgrade-also
          --no-shortcuts
      -
        name: Setup Cygwin environment
        id: setup-cygwin
        working-directory: C:\cygwin
        run: |
          printf '\nPATH=${{ steps.vars.outputs.cygwin-path }}\nexport PATH\n' >>$HOME/.bash_profile
          /bin/mkdir -p "$HOME"
          /bin/mkdir -p /src/downloads
          /bin/mkdir -p /installed
          /bin/mkdir -p /files-unsigned
          /bin/perl -pe 's/\r\n|\n|\r/\r\n/g' < "$(/bin/cygpath "$GITHUB_WORKSPACE/build-exe/license-for-distribution.txt")" > /files-unsigned/license.txt
      -
        name: Download iconv
        working-directory: C:\cygwin\src\downloads
        shell: pwsh
        run: |
          if (Test-Path -LiteralPath "libiconv-$env:ICONV_VERSION.tar.gz" -PathType Leaf) {
            Write-Host -Object 'Already downloaded'
          } else {
            Invoke-WebRequest "https://ftp.gnu.org/pub/gnu/libiconv/libiconv-$env:ICONV_VERSION.tar.gz" -OutFile "libiconv-$env:ICONV_VERSION.tar.gz"
            Write-Host -Object 'Downloaded'
          }
      -
        name: Extract iconv
        working-directory: C:\cygwin\src
        run: tar x -z -f downloads/libiconv-$ICONV_VERSION.tar.gz
      -
        name: Configure iconv
        id: iconv-configure
        working-directory: C:\cygwin\src\libiconv-${{ env.ICONV_VERSION }}
        run: |
          mkdir build
          cd build
          ../configure \
            CPPFLAGS='${{ steps.vars.outputs.cpp-flags }}'
            LDFLAGS='${{ steps.vars.outputs.ld-flags }}'
            ${{ steps.vars.outputs.configure-args }}
            --prefix=/installed
      -
        name: Compile iconv
        working-directory: C:\cygwin\src\libiconv-${{ env.ICONV_VERSION }}\build
        run: make --jobs=$(nproc)
      -
        name: Install iconv
        working-directory: C:\cygwin\src\libiconv-${{ env.ICONV_VERSION }}\build
        run: make install && cp ../COPYING /installed/iconv-license.txt
      -
        name: Copy built assets
        run: ./test-signpath/create-output.sh /installed /files-unsigned '${{ steps.vars.outputs.mingw-host }}'
      -
        name: Process dependencies
        shell: pwsh
        run: ./build-exe/process-dependencies.ps1 ${{ matrix.bits }} ${{ matrix.link }} C:\cygwin\files-unsigned C:\cygwin\usr\${{ steps.vars.outputs.mingw-host }}
      -
        name: Upload unsigned files
        id: upload-files-unsigned
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.link }}-${{ matrix.bits }}-files-unsigned
          path: C:\cygwin\files-unsigned
          if-no-files-found: error
          retention-days: 1
      -
        name: Sign files
        id: sign-files
        uses: signpath/github-action-submit-signing-request@v1
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: 98c3accc-92c9-4962-b150-ff1f5c6356b8
          project-slug: gettext-iconv-windows
          signing-policy-slug: test-signing
          github-artifact-id: ${{ steps.upload-files-unsigned.outputs.artifact-id }}
          wait-for-completion: true
          output-artifact-directory: C:\files-signed
      -
        name: Signing request details
        shell: pwsh
        run: "Signing request ID: ${{ steps.sign-files.outputs.signing-request-id }}"
      -
        name: Create signed files archive
        working-directory: C:\files-signed
        shell: cmd
        run: 7z.exe a -bd -bt -mx9 -r -sse -tzip C:\gettext${{ env.GETTEXT_VERSION }}-iconv${{ env.ICONV_VERSION }}-${{ matrix.link }}-${{ matrix.bits }}.zip
      -
        name: Upload signed files archive
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.link }}-${{ matrix.bits }}-files
          path: C:\gettext${{ env.GETTEXT_VERSION }}-iconv${{ env.ICONV_VERSION }}-${{ matrix.link }}-${{ matrix.bits }}.zip
          if-no-files-found: error
          compression-level: 0
      -
        name: Create installer
        shell: pwsh
        run: ./build-exe/create-installer.ps1 -Bits ${{ matrix.bits }} -Link ${{ matrix.link }} -SourceDirectory C:\files-signed -OutputDirectory C:\
      -
        name: Upload unsigned installer
        id: upload-installer-unsigned
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.link }}-${{ matrix.bits }}-installer-unsigned
          path: C:\gettext${{ env.GETTEXT_VERSION }}-iconv${{ env.ICONV_VERSION }}-${{ matrix.link }}-${{ matrix.bits }}.exe
          if-no-files-found: error
          compression-level: 0
          retention-days: 1
      -
        name: Sign installer
        id: sign-installer
        uses: signpath/github-action-submit-signing-request@v1
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: 98c3accc-92c9-4962-b150-ff1f5c6356b8
          project-slug: gettext-iconv-windows
          signing-policy-slug: test-signing
          github-artifact-id: ${{ steps.upload-installer-unsigned.outputs.artifact-id }}
          wait-for-completion: true
          output-artifact-directory: C:\installer-signed
      -
        name: Signing request details
        shell: pwsh
        run: "Signing request ID: ${{ steps.sign-installer.outputs.signing-request-id }}"
      -
        name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.link }}-${{ matrix.bits }}-installer
          path: C:\installer-signed\gettext${{ env.GETTEXT_VERSION }}-iconv${{ env.ICONV_VERSION }}-${{ matrix.link }}-${{ matrix.bits }}.exe
          if-no-files-found: error
          compression-level: 0
